version: 2

models:
  - name: sales
    tests:
      - unique:
          column_name: "(orders_id || '-' || products_id)"

    columns:
      - name: orders_id
        description: PK-identifier of the orders
        tests:
          - not_null

      - name: products_id
        description: PK-identifier of the products
        tests:
          - not_null

      - name: qty

      - name: turnover
        description: turnover of orders 
        tests:
          - not_null

      - name: purchase_cost
        description: purchase of each cost
        tests:
          - not_null

      - name: margin
        description: margin of each cost
